### ISSUE TITLE
Passing variables conditionally between an execute block and a report block

### ISSUE THREAD

**Issue by dmaizel** [RedHatQE/teflo#119]
At the moment there is no way to pass variables from an execute block to a report block conditionally.

An example use case:
Let's say I want to execute some tests and then report to a different test run in Polarion per environment.
Ideally, I would want to export an environment variable conditionally inside a shell and then use it in the corresponding report block.

To work around this I use 1 common scenario file which handles orchestration, provisioning, and execution. And then, I create a separate scenario file per environment which consists only of a report block and includes the common file.

**Comment by dno-github** [comment]
Jira ticket CCITCARBON-361 has been created for this issue. Url : https://issues.redhat.com/browse/CCITCARBON-361

**Comment by rujutashinde** [comment]
Hello @dmaizel 

I apologize for the delay in response to this ticket [1]. It was moved around wrt to priority

After looking at the code, we were unable to fit in this use case. The reasons being:

1. We recently added a way to provide additional environmental variables along with the set environmental variables within the orchestrate and execute block [2] This will pick the newest set env variables during each execute or orchestrate task. 

2. Even with the above change, the report block still will not be able to pick the environment variables, as the environment variables are not being persisted along ssh sessions. And every teflo task is its own ssh session.

3. Also if you are using jinja templating in the report block where you are using an env variable as a check. something like below , where uname is an env variable set in the prior execute task.,
It will not work  as the jinja templating is resolved in the beginning of the teflo run [3], and whatever value of uname is present will get replaced in the scenario in  report block.

```
report:
  - name: SampleTest.xml
    description: import results to polarion
    credential: polarion-creds
    importer: polarion
    project_id: Carbon1
    {% if uname  == 'teflo' %}
    testsuite_properties:
      polarion-lookup-method: name
      polarion-testrun-title: e2e-tests
    {% else %}
    testsuite_properties:
      polarion-lookup-method: name
      polarion-testrun-title: {{ uname }}
    {% endif %}

```
If you like to further discuss this we could have a quick meeting and see what else can be done.

[1] t https://github.com/RedHatQE/teflo/issues/119
[2] https://github.com/RedHatQE/teflo/commit/588f94658cd7e490ef5111234c563e242a345735
[3] https://github.com/RedHatQE/teflo/blob/develop/teflo/helpers.py#L1538-L1563
