### ISSUE TITLE
custom resource_check does not honor the  ansible_galaxy_options

### ISSUE THREAD

**Issue by Dannyb48** [RedHatQE/teflo#145]
With teflo 1.2.x and the following in my resource check below. It does not actually download the required collections.

```
--
name: Init and Validate C0 collection

resource_check:
  playbook:
    - name: css_psi_customerzero/ansible/playbooks/validate_c0_collection.yml
      ansible_galaxy_options:
        role_file: css_psi_customrezero/requirements.yml
```
You can see the value get's loaded into the ansible_service https://github.com/RedHatQE/teflo/blob/develop/teflo/utils/resource_checker.py#L82

but it never gets downloaded, it just calls `run_playbook` function
https://github.com/RedHatQE/teflo/blob/develop/teflo/utils/resource_checker.py#L96

Should add a conditional check to see if the field is populated and call the `download_roles` function before calling `run_playbook`
