### ISSUE TITLE
Unable to pass multiple files to the extra_vars module

### ISSUE THREAD

**Issue by DharmitD** [RedHatQE/teflo#73]
When multiple files are passed as a list in the `extra_vars` module within `ansible_options`, the task fails. The `file` module only works for a single file.

For example, the following code snippet doesn't work:

```
orchestrate:
  - name: ansible/sys_setup.yml
    description: Clones layered product testsuite
    orchestrator: ansible
    hosts: "interconnect{{ INSTANCE_TAG }}"
    connection: local
    ansible_options:
      extra_vars:
        file:
          - ansible/vars/amq-interconnect_v1.10.yml
          - ansible/amq-interconnect_creds.yml
```

At present, the `extra_vars` is looped through by `file` which a unique key so it can only be set once:
https://github.com/RedHatQE/teflo/blob/master/teflo/ansible_helpers.py#L178
There needs to be a provision to pass a list to the `file` module
